services:
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    image: ${DOCKER_REPO}ttv-client:latest
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env
    image: ${DOCKER_REPO}ttv-api:latest
    container_name: api
    ports:
      - "5002:5002"
    volumes:
      - ${DATA_DIR}:/usr/src/saved_data

  pyserver:
    build:
      context: ./py-server
      dockerfile: Dockerfile
    environment:
      - MODE=production
    env_file:
      - ./py-server/.env
    image: ${DOCKER_REPO}ttv-py-server:latest
    container_name: pyserver
    ports:
      - "5003:5003"
    volumes:
      - ${DATA_DIR}:/usr/src/saved_data

  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ${DOCKER_REPO}ttv-nginx:latest
    container_name: nginx
    ports:
      - "3050:80"
